### ISSUE TITLE
ubuntu 14で再起動後の挙動がおかしい

### ISSUE THREAD

**Issue by pyama86** [STNS/libnss_stns#37]
![image](https://cloud.githubusercontent.com/assets/8022082/18232994/9d796bb6-7316-11e6-8394-49e98af6f076.png)

cgoのpthread_createエラーが出ており、そこからうまく立ち上がれない。

**Comment by manabusakai** [comment]
0.2.1 を Ubuntu の各バージョンで確認しました。
- Ubuntu 12.04 LTS ... NG
- Ubuntu 14.04 LTS ... NG
- Ubuntu 15.10 ... OK
- Ubuntu 16.04 LTS ... OK

Ubuntu 14.04 以下で発生しているようです。

**Comment by pyama86** [comment]
なるほど。

![image](https://cloud.githubusercontent.com/assets/8022082/18255124/df6844dc-73e0-11e6-9f0e-b364e7354d7e.png)

インターフェースのup/downを確認したり、`/sbin/runlevel`を参照してみても、どうも起動に影響を与えそうなので、なんかしらシステム・コールから取得出来る値で制御出来ないか考えてみます。

**Comment by pyama86** [comment]
時間がかかりましたが、なんとかなりそうなので動作検証してリリースします。

**Comment by pyama86** [comment]
libnss-stns 0.2-2にて修正されました。
